import { AIProvider, AIProviderMeta } from '../types';

export const AI_PROVIDERS: Record<AIProvider, AIProviderMeta> = {
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    shortName: 'Gemini',
    tagline: 'Fast, high-quality reasoning with generous free tier',
    placeholder: 'AIzaSy...',
    keyPrefix: 'AIza',
    helpUrl: 'https://aistudio.google.com/app/apikey',
    helpLabel: 'Get key from Google AI Studio',
    recommendedModel: 'gemini-2.5-flash',
    icon: 'Sparkles',
    color: 'blue',
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-400',
    badgeBorder: 'border-blue-500/20',
  },
  claude: {
    id: 'claude',
    name: 'Anthropic Claude',
    shortName: 'Claude',
    tagline: 'Superb writing style, nuanced career summaries, and natural tone',
    placeholder: 'sk-ant-api03-...',
    keyPrefix: 'sk-ant-',
    helpUrl: 'https://console.anthropic.com/settings/keys',
    helpLabel: 'Get key from Anthropic Console',
    recommendedModel: 'claude-3-5-sonnet-20241022',
    icon: 'Bot',
    color: 'amber',
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-400',
    badgeBorder: 'border-amber-500/20',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI (ChatGPT)',
    shortName: 'OpenAI',
    tagline: 'Industry standard for structured data generation and editing',
    placeholder: 'sk-proj-... or sk-...',
    keyPrefix: 'sk-',
    helpUrl: 'https://platform.openai.com/api-keys',
    helpLabel: 'Get key from OpenAI Platform',
    recommendedModel: 'gpt-4o-mini',
    icon: 'Cpu',
    color: 'emerald',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400',
    badgeBorder: 'border-emerald-500/20',
  },
};

export const PROVIDER_LIST: AIProviderMeta[] = Object.values(AI_PROVIDERS);
